-- MySQL Script generated by MySQL Workbench
-- Tue Apr  7 21:11:40 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema autoescola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `autoescola` ;

-- -----------------------------------------------------
-- Schema autoescola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autoescola` DEFAULT CHARACTER SET utf8mb3 ;
USE `autoescola` ;

-- -----------------------------------------------------
-- Table `autoescola`.`agendamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoescola`.`agendamento` ;

CREATE TABLE IF NOT EXISTS `autoescola`.`agendamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_instrutor` INT NOT NULL,
  `id_aluno` INT NOT NULL,
  `id_veiculo` INT NOT NULL,
  `datetime` DATETIME NOT NULL,
  `cat` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `datetime_UNIQUE` (`datetime` ASC) VISIBLE,
  INDEX `agendamento_fk_1_idx` (`id_aluno` ASC) VISIBLE,
  INDEX `agendamento_fk_2_idx` (`id_instrutor` ASC) VISIBLE,
  INDEX `agendamento_fk_3_idx` (`id_veiculo` ASC) VISIBLE,
  CONSTRAINT `agendamento_fk_1`
    FOREIGN KEY (`id_aluno`)
    REFERENCES `autoescola`.`aluno` (`id`),
  CONSTRAINT `agendamento_fk_2`
    FOREIGN KEY (`id_instrutor`)
    REFERENCES `autoescola`.`instrutor` (`id`),
  CONSTRAINT `agendamento_fk_3`
    FOREIGN KEY (`id_veiculo`)
    REFERENCES `autoescola`.`veiculo` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `autoescola`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoescola`.`aluno` ;

CREATE TABLE IF NOT EXISTS `autoescola`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `cat` VARCHAR(2) NULL DEFAULT NULL,
  `renach` VARCHAR(11) NULL DEFAULT NULL,
  `valor` FLOAT NULL DEFAULT NULL,
  `entrada` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 58
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `autoescola`.`gestor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoescola`.`gestor` ;

CREATE TABLE IF NOT EXISTS `autoescola`.`gestor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `autoescola`.`instrutor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoescola`.`instrutor` ;

CREATE TABLE IF NOT EXISTS `autoescola`.`instrutor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `autoescola`.`veiculo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `autoescola`.`veiculo` ;

CREATE TABLE IF NOT EXISTS `autoescola`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(10) NOT NULL,
  `placa` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
